# mkdocs.yml
site_name: protodantic
site_url: "https://qdeli187.github.io/protodantic"
repo_url: "https://github.com/qdeli187/protodantic"
theme:
  name: shadcn
  show_title: false # show the title in the top bar
  show_stargazers: true # show the stargazers in the top bar
  pygments_style: # default styles
    light: shadcn-light
    dark: dracula
  icon: heroicons:rocket-launch # use the shadcn svg if not defined
  topbar_sections: false # NEW!
  show_datetime: false
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - codehilite
  - admonition
plugins:
  - search
# nav:
#   - Home: index.md
#   - Getting Started: getting-started.md
#   - Roadmap: roadmap.md
#   - Contributing: contributing.md
