name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name}}
      release_created: ${{ steps.release.outputs.release_created}}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: python
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    steps:
      - name: âœ¨ Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: ğŸ¤– Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: ğŸ Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: ğŸ§° Install Poetry
        run: pip install poetry
      - name: ğŸ“¦ Install dependencies
        run: poetry install --with dev --with test
      - name: ğŸ§ª Run tests
        run: poetry run pytest
      - name: ğŸ— Build package
        run: poetry build
      # - name: ğŸ–¼ï¸ Build docs
      #   run: poetry run mkdocs gh-deploy --force
      - name: ğŸ“¦ Publish package
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          echo "Publishing version: ${{ needs.release-please.outputs.tag_name }}"
          poetry config pypi-token.pypi $PYPI_API_TOKEN
          poetry publish
